schema_version: 1

context:
  version: "0.1.2"

package:
  name: r-yr
  version: ${{ version }}

source:
  url: https://github.com/y-crdt/yr/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b515c7bd871ddf17cf2830d2e113837f271db70d5fad33aa0c90bd12f627d69c
  patches:
    - patches/0001-libdir-cargo-build-target.patch
    - patches/0001-Remove-document-step.patch

build:
  skip: win
  number: 0
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/
  script:
    env:
      NOT_CRAN: "1"
      DISABLE_AUTOBREW: "1"
    content:
      - |
        # Make libR findable for Cargo and R wrapper scripts
        export RUSTFLAGS="-C link-arg=-L${PREFIX}/lib/R/lib ${RUSTFLAGS}"
        export LD_LIBRARY_PATH="${PREFIX}/lib/R/lib:${LD_LIBRARY_PATH:-}"
        export DYLD_LIBRARY_PATH="${PREFIX}/lib/R/lib:${DYLD_LIBRARY_PATH:-}"

        ${R} CMD INSTALL --build . ${R_ARGS}

        # Bundle third party licenses from statically linked crates
        cd src/rust
        cargo-bundle-licenses --format yaml --output "${SRC_DIR}/THIRDPARTY.yml"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - if: build_platform != target_platform
      then:
        - cross-r-base ${{ r_base }}.*
    - cargo-bundle-licenses
    - autoconf
    - automake
    - pkg-config
    - make
  host:
    - r-base
  run:
    - r-base

tests:
  - r:
      libraries:
        - yr
  - script:
      - Rscript -e 'yr::Doc$new()'

about:
  homepage: https://github.com/y-crdt/yr
  summary: Y-CRDT Bindings to R
  description: |
    Provides R bindings to y-crdt, a Rust implementation of the Yjs CRDT
    (Conflict-free Replicated Data Type) framework.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/y-crdt/yr

extra:
  recipe-maintainers:
    - AntoinePrv
